using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Meka
{
    public class CodeGenerator
    {
        //TODO Generate C code from the abstract syntax tree generated by the parser
    }
}
